sudo: false
language: ruby
rvm:
  - 2.3.0
cache: bundler
before_install:
  - gem update --system
before_script:
  - bash init-user-db.sh
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
