#!/bin/bash
set -e

POSTGRES_USER=postgres

CHALLENGE_48H_DB=challenge48h
CHALLENGE_48H_USER=challenge48h
CHALLENGE_48H_PASSWORD=challenge48h

psql -v ON_ERROR_STOP=1 -h localhost --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $CHALLENGE_48H_USER WITH PASSWORD '$CHALLENGE_48H_PASSWORD';
    ALTER USER $CHALLENGE_48H_USER CREATEDB;
EOSQL

